name: Terraform Plan

on:
  workflow_call:
    inputs:
      REGION:
        required: true
        type: string
      ENVIRONMENT:
        type: string
        required: true
      ENVNAME:
        type: string
        required: true
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
jobs:
    reusable_workflow_call-get-secret-manager:
        name: Get Variables in Secret Manager
        runs-on: ubuntu-latest
        
        environment: ${{ inputs.ENVIRONMENT }}
        steps:
        - name: Checkout 
          uses: actions/checkout@v3
        
        - name: Configuring AWS credentials
          id: aws-credentials
          env:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ inputs.REGION }}
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ inputs.REGION }}

        - name: Get Variable
          id: GetSecretManager
          run: |
            # sudo apt-get update && sudo apt-get install jq curl libpq-dev -y
            aws secretsmanager get-secret-value --secret-id ${{ inputs.ENVNAME }} --query SecretString --output text > secrets.json
            cat secrets.json | jq -r "to_entries|map(\"\(.key)=\\\"\(.value|tostring)\\\"\")|.[]" > .env
            sed -i 's/\"//g' .env
        
        - name: Fs Info
          id: FsInfo
          run: |
            ls -la
        
        - name: Upload variables
          uses: actions/upload-artifact@v4
          with:
            name: variables
            path: .env
